### ISSUE TITLE
Error in common.py start() function

### ISSUE THREAD

**Issue by daxm** [pozgo/docker-mkdocs#27]
In the common.py file I think the start() function needs to change directory into the DOCS_DIRECTORY.

Here is what I get in the docker logs when I try to start:
```
Installing python modules: mkdocs-windmill mkdocs-ivory
Executing [ pip install -q mkdocs-windmill mkdocs-ivory ]:


Process finished with return code 0
Output: 


Modules installed.
Detected previous installation in (/workdir).
Starting MKDocs
LIVE RELOAD - [ ENABLED ]
FAST_MODE - [ ENABLED ]
Executing [ mkdocs serve -a 0.0.0.0:8000  --dirtyreload ]:

INFO    -  Building documentation...

Config file '/mkdocs/mkdocs.yml' does not exist.

Process finished with return code 1
Output: 
INFO    -  Building documentation...

Config file '/mkdocs/mkdocs.yml' does not exist.
```

As you can see it finds my previous installation but then doesn 't load it.

**Comment by daxm** [comment]
Here is my docker-compose.yml file:
```
cat docker-compose.yml 
---
version: '3'

services:
  ten2one:
    image: polinux/mkdocs
    container_name: ten2one
    hostname: ten2one
    volumes:
      - ./content:/workdir
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - ADD_MODULES=mkdocs-windmill mkdocs-ivory
      - LIVE_RELOAD_SUPPORT=true
      - FAST_MODE=true
      - DOCS_DIRECTORY=/workdir
```
